### PR TITLE
For `pivot_wider()`, advise that the user identify duplicates using dplyr

### LINKED ISSUE #1113: Make pivot_wider error messages more useful, like spread errors
Hello, I have found that the pivot_ family error messages are much less helpful than spread and gather error messages. For example, here's an error message from the exact same dataset that had a few rows with repeated values, using pivot_wider vs spread.

The spread error message tells me exactly where the issue is. The pivot_wider one is very difficult to understand and doesn't point me to the error. When I added `values_fn = length` to the pivot call I got another error, `Error: 1 components of `...` were not used. We detected these problematic arguments: * `vaues_fn``
 Could you please consider incorporating some of the old context?

pivot_wider:
```
Warning message:
Values are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = length` to identify where the duplicates arise
* Use `values_fn = {summary_fun}` to summarise duplicates 
```

spread:
```
Error: Each row of output must be identified by a unique combination of keys.
Keys are shared for 6 rows:
* 427, 428
* 540, 541
* 800, 802
```
(edited to add text for error messages)

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #1113 

@hadley what do you think about this? I think this nicely improves on the `pivot_wider()` error message about values that aren't uniquely identified.

_Note_: I purposefully didn't use `count()` here. If you already have a grouped data frame that you were pivoting with and you pass that to `count()` then it will regroup with `.add = TRUE`, which will produce the wrong results for identifying duplicates.

The original reprex from https://github.com/tidyverse/tidyr/issues/1113#issuecomment-824944361:

``` r
library(tidyverse)

# Add a duplicate row
row_dupe <- fish_encounters %>% filter(row_number() == 20)
fish_dupe <- bind_rows(fish_encounters, row_dupe)

temp <- fish_dupe %>%
  pivot_wider(names_from = station, values_from = seen)
#> Warning: Values from `seen` are not uniquely identified; output will contain list-cols.
#> * Use `values_fn = list` to suppress this warning.
#> * Use `values_fn = {summary_fun}` to summarise duplicates.
#> * Use the following to identify duplicates.
#>   {data} %>%
#>     dplyr::group_by(fish, station) %>%
#>     dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
#>     dplyr::filter(n > 1L)

fish_dupe %>%
  dplyr::group_by(fish, station) %>%
  dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
  dplyr::filter(n > 1L) 
#> # A tibble: 1 × 3
#>   fish  station     n
#>   <fct> <fct>   <int>
#> 1 4843  BCW2        2
```

### CODE REVIEW

File: R/pivot-wide.R [hunk 1]
```diff
@@ -305,11 +306,19 @@ pivot_wider_spec <- function(data,
...
+    group_cols <- backtick_if_not_syntactic(group_cols)
+    group_cols <- glue::glue_collapse(group_cols, sep = ", ")
+
     warn(glue::glue(
       "Values from {duplicate_names} are not uniquely identified; output will contain list-cols.\n",
       "* Use `values_fn = list` to suppress this warning.\n",
-      "* Use `values_fn = length` to identify where the duplicates arise.\n",
-      "* Use `values_fn = {{summary_fun}}` to summarise duplicates."
+      "* Use `values_fn = {{summary_fun}}` to summarise duplicates.\n",
+      "* Use the following to identify duplicates.\n",
```
Comment (hadley) [inline R/pivot-wide.R:317]:
```suggestion
      "* Use the following dplyr code to identify duplicates.\n",
```

**Review by hadley — APPROVED** [review]
