### PR TITLE
Can pivot_longer() zero row data frames again.

### LINKED ISSUE #1142: Broken revdeps from #1132
@mgirlich it seems that #1132 has broken a few packages. Would you mind please taking a look at these? I think these are related to this line?
https://github.com/tidyverse/tidyr/commit/638607900303b3453d7a82b1d40f8cdf388d2f8b#diff-11218ff1e64c5ef5af6656234d2684855594347f5e91dfd39cb6fd1a01c2c0f2R239

# ffscrapr

<details>

* Version: 1.4.5
* GitHub: https://github.com/ffverse/ffscrapr
* Source code: https://github.com/cran/ffscrapr
* Date/Publication: 2021-07-25 14:30:05 UTC
* Number of recursive dependencies: 68

Run `cloud_details(, "ffscrapr")` for more info

</details>

## Newly broken

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-ff_transactions.R:15:5): ff_transactions returns a tibble of transactions ──
Error: Problem with `mutate()` column `adds`.
ℹ `adds = purrr::map(...)`.
✖ invalid 'ncol' value (too large or NA)
Backtrace:
     █
  1. ├─ffscrapr::ff_transactions(jml_conn, week = 1:9) test-ff_transactions.R:15:4
  2. ├─ffscrapr:::ff_transactions.sleeper_conn(jml_conn, week = 1:9)
  3. │ ├─`%>%`(...)
  4. │ └─purrr::map_dfr(transaction_functions, rlang::exec, raw_transactions)
  5. │   └─purrr::map(.x, .f, ...)
  6. │     ├─rlang:::.f(.x[[i]], ...)
  7. │     └─(function (raw_transactions) ...
  8. │       └─`%>%`(...)
  9. ├─dplyr::select(...)
 10. ├─dplyr::left_join(...)
 11. ├─dplyr::left_join(., players_endpoint, by = "player_id")
 12. ├─dplyr::arrange(., dplyr::desc(.data$timestamp))
 13. ├─dplyr::ungroup(.)
 14. ├─dplyr::mutate(...)
 15. ├─dplyr::group_by(., .data$timestamp)
 16. ├─dplyr::select(., -"name", -"status")
 17. ├─tidyr::unnest(., "value")
 18. ├─dplyr::filter(., !is.na(.data$value))
 19. ├─tidyr::pivot_longer(...)
 20. ├─dplyr::mutate(...)
 21. ├─dplyr:::mutate.data.frame(...)
 22. │ └─dplyr:::mutate_cols(.data, ..., caller_env = caller_env())
 23. │   ├─base::withCallingHandlers(...)
 24. │   └─mask$eval_all_mutate(quo)
 25. ├─purrr::map(...)
 26. │ └─ffscrapr:::.f(.x[[i]], ...)
 27. │   └─`%>%`(...)
 28. ├─dplyr::mutate_all(., as.character)
 29. │ └─dplyr:::check_grouped(.tbl, "mutate", "all", alt = TRUE)
 30. │   └─dplyr::is_grouped_df(tbl)
 31. ├─tidyr::pivot_longer(...)
 32. ├─tidyr:::pivot_longer.data.frame(...)
 33. │ └─tidyr::pivot_longer_spec(...)
 34. │   ├─base::t(matrix(seq_len(n_vals), ncol = n_vals/nrow(data)))
 35. │   └─base::matrix(seq_len(n_vals), ncol = n_vals/nrow(data))
 36. └─base::.handleSimpleError(...)
 37.   └─dplyr:::h(simpleError(msg, call))

[ FAIL 1 | WARN 0 | SKIP 1 | PASS 117 ]
Error: Test failures
Execution halted
```

# r2dii.analysis

<details>

* Version: 0.1.10
* GitHub: https://github.com/2DegreesInvesting/r2dii.analysis
* Source code: https://github.com/cran/r2dii.analysis
* Date/Publication: 2021-07-09 12:30:02 UTC
* Number of recursive dependencies: 70

Run `cloud_details(, "r2dii.analysis")` for more info

</details>

## Newly broken

*   checking examples ... ERROR
    ```
    Running examples in ‘r2dii.analysis-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: target_sda
    > ### Title: Add targets for CO2 emissions per unit production at the
    > ###   portfolio level, using the SDA approach
    > ### Aliases: target_sda
    > 
    > ### ** Examples
    > 
    ...
    > 
    > ald2 <- subset(ald, !is.na(emission_factor))
    > anyNA(ald2$emission_factor)
    [1] FALSE
    > 
    > out <- target_sda(matched, ald2, co2_intensity_scenario = co2_scenario)
    Error in matrix(seq_len(n_vals), ncol = n_vals/nrow(data)) : 
      invalid 'ncol' value (too large or NA)
    Calls: target_sda ... pivot_longer.data.frame -> pivot_longer_spec -> t -> matrix
    Execution halted
    ```

### PR DESCRIPTION
**Pull request by mgirlich**
This fixes #1142.

### CODE REVIEW

**Review by hadley — APPROVED** [review]
Looks like the build failures are transient

File: R/pivot-long.R [hunk 1]
```diff
@@ -236,7 +236,12 @@ pivot_longer_spec <- function(data,
     # TODO somehow `t(matrix(x))` is _faster_ than `matrix(x, byrow = TRUE)`
     # if this gets fixed in R this should use `byrow = TRUE` again
     n_vals <- nrow(data) * length(val_cols)
-    idx <- t(matrix(seq_len(n_vals), ncol = n_vals / nrow(data)))
+    if (nrow(data) == 0L) {
+      ncol <- 0
+    } else {
+      ncol <- length(val_cols)
+    }
+    idx <- t(matrix(seq_len(n_vals), ncol = ncol))
```
Comment (DavisVaughan) [inline R/pivot-long.R:244]: Can you just do this?

```r
idx <- t(matrix(seq_len(n_vals), ncol = length(val_cols)))
```

Previously you used `ncol = n_vals / nrow(data)`, but if `ncol = length(val_cols)` returns the correct result even in the 0-row case (since `val_cols` will be an empty list) then I think that would work nicely.

Comment (mgirlich) [reply R/pivot-long.R:244]: Yes, it does work. I was a bit confused at first because we get back a matrix with dimensions but `as.integer()` handles this fine.
